#!/usr/bin/env bash
# shellcheck disable=SC2155

log() {
	echo "deploy-patch: -> $*"
} >&2

warn() {
	printf "deploy-patch\e[1;33m[WARN]\e[m: -> %b\n" "$*"
} >&2


patch() {
	local scrape_dir="${1:?Missing scrape dir}"

	patchJSONBasePaths "${scrape_dir}/register" ../
	patchJSONBasePaths "${scrape_dir}/register/geodetic" ../../
	# patchJSONBasePaths "${scrape_dir}/item" ../

	patchPageLinksBasePaths "${scrape_dir}/register" ../
	patchPageLinksBasePaths "${scrape_dir}/register/geodetic" ../../
	patchPageLinksBasePaths "${scrape_dir}/item" ../
}

patchJSONBasePaths() {
	local target_dir="${1:?Missing target dir}"; shift
	local base_path="${1:?Missing base path}"; shift
	local depth="${1:-1}"

	while IFS= read -r file
	do
		log "Fixing[patchJSONBasePaths] ${file}"
		sed \
			-i \
			-e 's@\("sAjaxSource":\s*"\)/\(register\)@\1'"${base_path}"'\2@' \
			"${file}"
	done < <(fd -t f . -e html -d "${depth}" "${target_dir}")
}

patchPageLinksBasePaths() {
	local target_dir="${1:?Missing target dir}"; shift
	local base_path="${1:?Missing base path}"; shift
	local depth="${1:-1}"

	while IFS= read -r file
	do
		log "Fixing[patchPageLinksBasePaths] ${file}"
		sed \
			-i \
			-e 's@\(href="\)/@\1'"${base_path}"'@g' \
			-e 's@\(src="\)/@\1'"${base_path}"'@g' \
			-e "s@location.href = '/@location.href = '${base_path}@g" \
			"${file}"
	done < <(fd -t f . -e html -d "${depth}" "${target_dir}")
}

main() {
	export SCRAPE_ORIGIN_URL=https://geodetic.isotc211.org
	local domain="${SCRAPE_ORIGIN_URL#http*://}"
	domain="${domain%%/*}"
	local DEFAULT_SCRAPE_DIR="./${domain:?Missing domain}"

	if [[ $# -gt 1 ]]
	then
		show_usage
		exit 1
	else
		local scrape_dir="${1:-"${DEFAULT_SCRAPE_DIR}"}"
		patch "$scrape_dir"
	fi
}

show_usage() {
	cat <<EOF
deploy-patch [SCRAPE_DIR]

EXAMPLES
  > deploy-patch
EOF
} >&2


main "$@"
