#!/usr/bin/env bash

main() {
  local port="${1:-${HTTP_SERVE_PORT:-8000}}"
  local dir="${2:-${HTTP_SERVE_DIR:-${SCRAPE_DIR:-${DEFAULT_DOMAIN:-"./geodetic.isotc211.org"}}}}"
	darkhttpd "${dir}" --port "${port}"
}

main "$@"
